import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { GlobalProvider } from "./GlobalContext";

export const metadata: Metadata = {
  title: "Health Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      {/* I need to add a provider class here to manage data sync */}
      {/* Yes I do! 2025-09-13 I'll do that now */}
      <body>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
